-- Customer location table
CREATE TABLE IF NOT EXISTS customer_location (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  county VARCHAR(100),
  state CHAR(2)
);
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('James', 'Butt', 'Orleans', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Josephine', 'Darakjy', 'Livingston', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Art', 'Venere', 'Gloucester', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lenna', 'Paprocki', 'Anchorage', 'AK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Donette', 'Foller', 'Butler', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Simona', 'Morasca', 'Ashland', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mitsue', 'Tollner', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Leota', 'Dilliard', 'Santa Clara', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sage', 'Wieser', 'Minnehaha', 'SD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kris', 'Marrier', 'Baltimore City', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Minna', 'Amigon', 'Montgomery', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Abel', 'Maclead', 'Suffolk', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kiley', 'Caldarera', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Graciela', 'Ruta', 'Geauga', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cammy', 'Albares', 'Webb', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mattie', 'Poquette', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Meaghan', 'Garufi', 'Warren', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gladys', 'Rim', 'Milwaukee', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Yuki', 'Whobrey', 'Wayne', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Fletcher', 'Flosi', 'Winnebago', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Bette', 'Nicka', 'Delaware', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Veronika', 'Inouye', 'Santa Clara', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Willard', 'Kolmetz', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Steve', 'Emigh', 'Summit', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alisha', 'Slusarski', 'Middlesex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Allene', 'Iturbide', 'Portage', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Chanel', 'Caudy', 'Johnson', 'KS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ezekiel', 'Chui', 'Talbot', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Willow', 'Kusko', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Bernardo', 'Figeroa', 'Montgomery', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ammie', 'Corrio', 'Franklin', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Francine', 'Vocelka', 'Dona Ana', 'NM');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ernie', 'Stenseth', 'Bergen', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Albina', 'Glick', 'Middlesex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alishia', 'Sergi', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Solange', 'Shinko', 'Jefferson', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jose', 'Stockham', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rozella', 'Ostrosky', 'Ventura', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Valentine', 'Gillian', 'Bexar', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kati', 'Rulapaugh', 'Dickinson', 'KS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Youlanda', 'Schemmer', 'Crook', 'OR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dyan', 'Oldroyd', 'Johnson', 'KS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Roxane', 'Campain', 'Fairbanks North Star', 'AK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lavera', 'Perin', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Erick', 'Ferencz', 'Fairbanks North Star', 'AK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Fatima', 'Saylors', 'Hennepin', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jina', 'Briddick', 'Suffolk', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kanisha', 'Waycott', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Emerson', 'Bowley', 'Dane', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Blair', 'Malet', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Brock', 'Bolognia', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lorrie', 'Nestle', 'Coffee', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sabra', 'Uyetake', 'Richland', 'SC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Marjory', 'Mastella', 'Delaware', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Karl', 'Klonowski', 'Hunterdon', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tonette', 'Wenner', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Amber', 'Monarrez', 'Montgomery', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Shenika', 'Seewald', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Delmy', 'Ahle', 'Providence', 'RI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Deeanna', 'Juhas', 'Montgomery', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Blondell', 'Pugh', 'Providence', 'RI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jamal', 'Vanausdal', 'Middlesex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cecily', 'Hollack', 'Travis', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carmelina', 'Lindall', 'Douglas', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Maurine', 'Yglesias', 'Milwaukee', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tawna', 'Buvens', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Penney', 'Weight', 'Anchorage', 'AK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Elly', 'Morocco', 'Erie', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ilene', 'Eroman', 'Anne Arundel', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Vallie', 'Mondella', 'Ada', 'ID');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kallie', 'Blackwood', 'San Francisco', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Johnetta', 'Abdallah', 'Orange', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Bobbye', 'Rhym', 'San Mateo', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Micaela', 'Rhymes', 'Contra Costa', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tamar', 'Hoogland', 'Madison', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Moon', 'Parlato', 'Allegany', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Laurel', 'Reitler', 'Baltimore City', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Delisa', 'Crupi', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Viva', 'Toelkes', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Elza', 'Lipke', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Devorah', 'Chickering', 'Curry', 'NM');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Timothy', 'Mulqueen', 'Richmond', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Arlette', 'Honeywell', 'Duval', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dominque', 'Dickerson', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lettie', 'Isenhower', 'Cuyahoga', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Myra', 'Munns', 'Tarrant', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jim', 'Butt', 'Orleans', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lai', 'Gato', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Stephen', 'Emigh', 'Summit', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tyra', 'Shields', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tammara', 'Wardrip', 'San Mateo', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cory', 'Gibes', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Danica', 'Bruschke', 'McLennan', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Wilda', 'Giguere', 'Anchorage', 'AK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Elvera', 'Benimadho', 'Santa Clara', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carma', 'Vanheusen', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Malinda', 'Hochard', 'Marion', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Natalie', 'Fern', 'Sweetwater', 'WY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lisha', 'Centini', 'Fairfax', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Arlene', 'Klusman', 'Orleans', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alease', 'Buemi', 'Boulder', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Louisa', 'Cronauer', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Angella', 'Cetta', 'Honolulu', 'HI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cyndy', 'Goldammer', 'Dakota', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rosio', 'Cork', 'Guilford', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Celeste', 'Korando', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Twana', 'Felger', 'Washington', 'OR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Estrella', 'Samu', 'Rock', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Donte', 'Kines', 'Worcester', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tiffiny', 'Steffensmeier', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Edna', 'Miceli', 'Erie', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sue', 'Kownacki', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jesusa', 'Shin', 'Coffee', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rolland', 'Francescon', 'Passaic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Pamella', 'Schmierer', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Glory', 'Kulzer', 'Baltimore', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Shawna', 'Palaspas', 'Ventura', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Brandon', 'Callaro', 'Honolulu', 'HI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Scarlet', 'Cartan', 'Dougherty', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Oretha', 'Menter', 'Suffolk', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ty', 'Smith', 'Bergen', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Xuan', 'Rochin', 'San Mateo', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lindsey', 'Dilello', 'San Bernardino', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Devora', 'Perez', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Herman', 'Demesa', 'Rensselaer', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rory', 'Papasergi', 'Lackawanna', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Talia', 'Riopelle', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Van', 'Shire', 'Hunterdon', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lucina', 'Lary', 'Brevard', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Bok', 'Isaacs', 'Bronx', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rolande', 'Spickerman', 'Honolulu', 'HI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Howard', 'Paulas', 'Denver', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kimbery', 'Madarang', 'Morris', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Thurman', 'Manno', 'Atlantic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Becky', 'Mirafuentes', 'Union', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Beatriz', 'Corrington', 'Plymouth', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Marti', 'Maybury', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nieves', 'Gotter', 'Multnomah', 'OR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Leatha', 'Hagele', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Valentin', 'Klimek', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Melissa', 'Wiklund', 'Hancock', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sheridan', 'Zane', 'Riverside', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Bulah', 'Padilla', 'McLennan', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Audra', 'Kohnert', 'Davidson', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Daren', 'Weirather', 'Milwaukee', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Fernanda', 'Jillson', 'Caroline', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gearldine', 'Gellinger', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Chau', 'Kitzman', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Theola', 'Frey', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cheryl', 'Haroldson', 'Atlantic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Laticia', 'Merced', 'Hamilton', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carissa', 'Batman', 'Lane', 'OR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lezlie', 'Craghead', 'Johnston', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ozell', 'Shealy', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Arminda', 'Parvis', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Reita', 'Leto', 'Marion', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Yolando', 'Luczki', 'Onondaga', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lizette', 'Stem', 'Camden', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gregoria', 'Pawlowicz', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carin', 'Deleo', 'Pulaski', 'AR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Chantell', 'Maynerich', 'Ramsey', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dierdre', 'Yum', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Larae', 'Gudroe', 'Terrebonne', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Latrice', 'Tolfree', 'Suffolk', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kerry', 'Theodorov', 'Sacramento', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dorthy', 'Hidvegi', 'Ada', 'ID');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Fannie', 'Lungren', 'Williamson', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Evangelina', 'Radde', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Novella', 'Degroot', 'Hawaii', 'HI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Clay', 'Hoa', 'Washoe', 'NV');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jennifer', 'Fallick', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Irma', 'Wolfgramm', 'Morris', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Eun', 'Coody', 'Spartanburg', 'SC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sylvia', 'Cousey', 'Carroll', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nana', 'Wrinkles', 'Westchester', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Layla', 'Springe', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Joesph', 'Degonia', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Annabelle', 'Boord', 'Middlesex', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Stephaine', 'Vinning', 'San Francisco', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nelida', 'Sawchuk', 'Bergen', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Marguerita', 'Hiatt', 'Contra Costa', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carmela', 'Cookey', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Junita', 'Brideau', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Claribel', 'Varriano', 'Wood', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Benton', 'Skursky', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Hillary', 'Skulski', 'Citrus', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Merilyn', 'Bayless', 'Santa Clara', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Teri', 'Ennaco', 'Luzerne', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Merlyn', 'Lawler', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Georgene', 'Montezuma', 'Contra Costa', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jettie', 'Mconnell', 'Somerset', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lemuel', 'Latzke', 'Suffolk', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Melodie', 'Knipp', 'Ventura', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Candida', 'Corbley', 'Somerset', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Karan', 'Karpin', 'Washington', 'OR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Andra', 'Scheyer', 'Marion', 'OR');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Felicidad', 'Poullion', 'Burlington', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Belen', 'Strassner', 'Douglas', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gracia', 'Melnyk', 'Duval', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jolanda', 'Hanafan', 'Penobscot', 'ME');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Barrett', 'Toyama', 'Tarrant', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Helga', 'Fredicks', 'Erie', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ashlyn', 'Pinilla', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Fausto', 'Agramonte', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ronny', 'Caiafa', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Marge', 'Limmel', 'Okaloosa', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Norah', 'Waymire', 'San Francisco', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Aliza', 'Baltimore', 'Santa Clara', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mozell', 'Pelkowski', 'San Mateo', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Viola', 'Bitsuie', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Franklyn', 'Emard', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Willodean', 'Konopacki', 'Lafayette', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Beckie', 'Silvestrini', 'Wayne', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rebecka', 'Gesick', 'Travis', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Frederica', 'Blunk', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Glen', 'Bartolet', 'King', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Freeman', 'Gochal', 'Chester', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Vincent', 'Meinerding', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rima', 'Bevelacqua', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Glendora', 'Sarbacher', 'Sonoma', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Avery', 'Steier', 'Orange', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cristy', 'Lother', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nicolette', 'Brossart', 'Worcester', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tracey', 'Modzelewski', 'Montgomery', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Virgina', 'Tegarden', 'Milwaukee', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tiera', 'Frankel', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alaine', 'Bergesen', 'Westchester', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Earleen', 'Mai', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Leonida', 'Gobern', 'Harrison', 'MS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kristopher', 'Marrier', 'Baltimore City', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Justine', 'Mugnolo', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Eladia', 'Saulter', 'Bergen', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Chaya', 'Malvin', 'Washtenaw', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gwenn', 'Suffield', 'Suffolk', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Salena', 'Karpel', 'Stark', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Yoko', 'Fishburne', 'New Haven', 'CT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Taryn', 'Moyd', 'Fairfax City', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Katina', 'Polidori', 'Middlesex', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rickie', 'Plumer', 'Lucas', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alex', 'Loader', 'Pierce', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lashon', 'Vizarro', 'Placer', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lauran', 'Burnard', 'Fremont', 'WY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ceola', 'Setter', 'Knox', 'ME');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('My', 'Rantanen', 'Bucks', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lorrine', 'Worlds', 'Hillsborough', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Peggie', 'Sturiale', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Marvel', 'Raymo', 'Brazos', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Daron', 'Dinos', 'Lake', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('An', 'Fritz', 'Atlantic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Portia', 'Stimmel', 'Somerset', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rhea', 'Aredondo', 'Kings', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Benedict', 'Sama', 'Saint Louis City', 'MO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alyce', 'Arias', 'San Joaquin', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Heike', 'Berganza', 'Passaic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carey', 'Dopico', 'Marion', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dottie', 'Hellickson', 'King', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Deandrea', 'Hughey', 'Alamance', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kimberlie', 'Duenas', 'Ellis', 'KS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Martina', 'Staback', 'Orange', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Skye', 'Fillingim', 'Hennepin', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jade', 'Farrar', 'Richland', 'SC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Charlene', 'Hamilton', 'Sonoma', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Geoffrey', 'Acey', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Stevie', 'Westerbeck', 'Orange', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Pamella', 'Fortino', 'Denver', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Harrison', 'Haufler', 'New Haven', 'CT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Johnna', 'Engelberg', 'Snohomish', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Buddy', 'Cloney', 'Cuyahoga', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dalene', 'Riden', 'Rockingham', 'NH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jerry', 'Zurcher', 'Brevard', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Haydee', 'Denooyer', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Joseph', 'Cryer', 'Orange', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Deonna', 'Kippley', 'Oakland', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Raymon', 'Calvaresi', 'Marion', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alecia', 'Bubash', 'Wichita', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ma', 'Layous', 'New Haven', 'CT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Detra', 'Coyier', 'Harford', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Terrilyn', 'Rodeigues', 'Orleans', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Salome', 'Lacovara', 'Richmond City', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dan', 'Perruzza', 'Orange', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Matthew', 'Neither', 'Scott', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Theodora', 'Restrepo', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Noah', 'Kalafatis', 'Milwaukee', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carmen', 'Sweigard', 'Somerset', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lavonda', 'Hengel', 'Cass', 'ND');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Junita', 'Stoltzman', 'Carson City', 'NV');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Herminia', 'Nicolozakes', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Casie', 'Good', 'Davidson', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Reena', 'Maisto', 'Wicomico', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mirta', 'Mallett', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cathrine', 'Pontoriero', 'Randall', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alexander', 'Loader', 'Pierce', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Raul', 'Upthegrove', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sarah', 'Candlish', 'Fulton', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lucy', 'Treston', 'Worcester', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Judy', 'Aquas', 'Berrien', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Yvonne', 'Tjepkema', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kayleigh', 'Lace', 'Lafayette', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Felix', 'Hirpara', 'Lancaster', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tresa', 'Sweely', 'Saint Louis', 'MO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kristeen', 'Turinetti', 'Tarrant', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jenelle', 'Regusters', 'Hillsborough', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Renea', 'Monterrubio', 'Fulton', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Olive', 'Matuszak', 'Riverside', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ligia', 'Reiber', 'Ingham', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Christiane', 'Eschberger', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Goldie', 'Schirpke', 'Penobscot', 'ME');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Loreta', 'Timenez', 'Prince Georges', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Fabiola', 'Hauenstein', 'York', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Amie', 'Perigo', 'Dallas', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Raina', 'Brachle', 'Silver Bow', 'MT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Erinn', 'Canlas', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cherry', 'Lietz', 'Oakland', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kattie', 'Vonasek', 'Cuyahoga', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lilli', 'Scriven', 'Taylor', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Whitley', 'Tomasulo', 'Tarrant', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Barbra', 'Adkin', 'Kings', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Hermila', 'Thyberg', 'Providence', 'RI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jesusita', 'Flister', 'Lancaster', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Caitlin', 'Julia', 'Providence', 'RI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Roosevelt', 'Hoffis', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Helaine', 'Halter', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lorean', 'Martabano', 'Bexar', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('France', 'Buzick', 'Kings', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Justine', 'Ferrario', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Adelina', 'Nabours', 'Cuyahoga', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Derick', 'Dhamer', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jerry', 'Dallen', 'Richmond City', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Leota', 'Ragel', 'Chattooga', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Caitie', 'Julia', 'Providence', 'RI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Aja', 'Gehrett', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kirk', 'Herritt', 'Broome', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Leonora', 'Mauson', 'Passaic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Winfred', 'Brucato', 'Latah', 'ID');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tarra', 'Nachor', 'San Francisco', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Corinne', 'Loder', 'Bristol', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dulce', 'Labreche', 'Oakland', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kate', 'Keneipp', 'Brown', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kaitlyn', 'Ogg', 'Baltimore City', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sherita', 'Saras', 'El Paso', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lashawnda', 'Stuer', 'Lucas', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ernest', 'Syrop', 'Prince Georges', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nobuko', 'Halsey', 'Bristol', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lavonna', 'Wolny', 'Fairfax', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lashaunda', 'Lizama', 'Anne Arundel', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mariann', 'Bilden', 'Travis', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Helene', 'Rodenberger', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Roselle', 'Estell', 'Crawford', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Samira', 'Heintzman', 'King', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Margart', 'Meisel', 'Hamilton', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kristofer', 'Bennick', 'Monroe', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Weldon', 'Acuff', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Shalon', 'Shadrick', 'Kings', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Denise', 'Patak', 'Orange', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Louvenia', 'Beech', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Audry', 'Yaw', 'Hillsborough', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kristel', 'Ehmann', 'El Paso', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Vincenza', 'Zepp', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Elouise', 'Gwalthney', 'Prince Georges', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Venita', 'Maillard', 'Orange', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kasandra', 'Semidey', 'Saint Louis City', 'MO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Xochitl', 'Discipio', 'Williamson', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Maile', 'Linahan', 'Guilford', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Krissy', 'Rauser', 'Suffolk', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Pete', 'Dubaldi', 'Bergen', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Linn', 'Paa', 'Shelby', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Paris', 'Wide', 'Fulton', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Wynell', 'Dorshorst', 'San Mateo', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Quentin', 'Birkner', 'Dakota', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Regenia', 'Kannady', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sheron', 'Louissant', 'Queens', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Izetta', 'Funnell', 'Dekalb', 'GA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rodolfo', 'Butzen', 'Rice', 'MN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Zona', 'Colla', 'Fairfield', 'CT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Serina', 'Zagen', 'Allen', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Paz', 'Sahagun', 'Lauderdale', 'MS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Markus', 'Lukasik', 'Macomb', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jaclyn', 'Bachman', 'El Paso', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cyril', 'Daufeldt', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gayla', 'Schnitzler', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Erick', 'Nievas', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jennie', 'Drymon', 'Lackawanna', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mitsue', 'Scipione', 'Butte', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ciara', 'Ventura', 'Orange', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Galen', 'Cantres', 'Cuyahoga', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Truman', 'Feichtner', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gail', 'Kitty', 'Anchorage', 'AK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dalene', 'Schoeneck', 'Philadelphia', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gertude', 'Witten', 'Hamilton', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lizbeth', 'Kohl', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Glenn', 'Berray', 'Polk', 'IA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lashandra', 'Klang', 'Montgomery', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lenna', 'Newville', 'Wake', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Laurel', 'Pagliuca', 'Benton', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mireya', 'Frerking', 'Westchester', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Annelle', 'Tagala', 'Baltimore', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dean', 'Ketelsen', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Levi', 'Munis', 'Worcester', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sylvie', 'Ryser', 'Tulsa', 'OK');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sharee', 'Maile', 'Muskegon', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cordelia', 'Storment', 'Lafayette', 'LA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mollie', 'Mcdoniel', 'Wood', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Brett', 'Mccullan', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Teddy', 'Pedrozo', 'Fairfield', 'CT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tasia', 'Andreason', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Hubert', 'Walthall', 'Summit', 'OH');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Arthur', 'Farrow', 'Bergen', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Vilma', 'Berlanga', 'Kent', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Billye', 'Miro', 'Rankin', 'MS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Glenna', 'Slayton', 'Shelby', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mitzie', 'Hudnall', 'Arapahoe', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Bernardine', 'Rodefer', 'Shelby', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Staci', 'Schmaltz', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nichelle', 'Meteer', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Janine', 'Rhoden', 'Queens', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ettie', 'Hoopengardner', 'Benton', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Eden', 'Jayson', 'Baltimore City', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lynelle', 'Auber', 'Essex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Merissa', 'Tomblin', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Golda', 'Kaniecki', 'Ocean', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Catarina', 'Gleich', 'Morris', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Virgie', 'Kiel', 'Denver', 'CO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jolene', 'Ostolaza', 'Newport News City', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Keneth', 'Borgman', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rikki', 'Nayar', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Elke', 'Sengbusch', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Hoa', 'Sarao', 'Volusia', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Trinidad', 'Mcrae', 'San Francisco', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mari', 'Lueckenbach', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Selma', 'Husser', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Antione', 'Onofrio', 'San Bernardino', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Luisa', 'Jurney', 'Middlesex', 'MA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Clorinda', 'Heimann', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dick', 'Wenzinger', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ahmed', 'Angalich', 'Dauphin', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Iluminada', 'Ohms', 'Maricopa', 'AZ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Joanna', 'Leinenbach', 'Palm Beach', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Caprice', 'Suell', 'Davidson', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Stephane', 'Myricks', 'Boone', 'KY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Quentin', 'Swayze', 'Monroe', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Annmarie', 'Castros', 'Montgomery', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Shonda', 'Greenbush', 'Passaic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cecil', 'Lapage', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jeanice', 'Claucherty', 'Miami-Dade', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Josphine', 'Villanueva', 'Clay', 'TN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Daniel', 'Perruzza', 'Orange', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cassi', 'Wildfong', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Britt', 'Galam', 'Montgomery', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Adell', 'Lipkin', 'Morris', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jacqueline', 'Rowling', 'Erie', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lonny', 'Weglarz', 'Salt Lake', 'UT');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lonna', 'Diestel', 'Cumberland', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cristal', 'Samara', 'Los Angeles', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Kenneth', 'Grenet', 'Ingham', 'MI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Elli', 'Mclaird', 'Oneida', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alline', 'Jeanty', 'St Joseph', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sharika', 'Eanes', 'Orange', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nu', 'Mcnease', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Daniela', 'Comnick', 'Mercer', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Cecilia', 'Colaizzo', 'Dane', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Leslie', 'Threets', 'Westchester', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nan', 'Koppinger', 'Guilford', 'NC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Izetta', 'Dewar', 'Baltimore City', 'MD');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Tegan', 'Arceo', 'Middlesex', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ruthann', 'Keener', 'Kerr', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Joni', 'Breland', 'Cook', 'IL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Vi', 'Rentfro', 'Monmouth', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Colette', 'Kardas', 'Douglas', 'NE');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Malcolm', 'Tromblay', 'Fairfax', 'VA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Ryan', 'Harnos', 'Collin', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jess', 'Chaffins', 'New York', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Sharen', 'Bourbon', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Nickolas', 'Juvera', 'Citrus', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gary', 'Nunlee', 'Hancock', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Diane', 'Devreese', 'Buchanan', 'MO');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Roslyn', 'Chavous', 'Hinds', 'MS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Glory', 'Schieler', 'Taylor', 'TX');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Rasheeda', 'Sayaphon', 'Santa Clara', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alpha', 'Palaia', 'Camden', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Refugia', 'Jacobos', 'Alameda', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Shawnda', 'Yori', 'Seminole', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Mona', 'Delasancha', 'Laramie', 'WY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gilma', 'Liukko', 'Nassau', 'NY');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Janey', 'Gabisi', 'Dane', 'WI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lili', 'Paskin', 'Hudson', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Loren', 'Asar', 'Lackawanna', 'PA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Dorothy', 'Chesterfield', 'San Diego', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Gail', 'Similton', 'Riverside', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Catalina', 'Tillotson', 'Atlantic', 'NJ');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lawrence', 'Lorens', 'Providence', 'RI');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Carlee', 'Boulter', 'Dickinson', 'KS');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Thaddeus', 'Ankeny', 'Placer', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jovita', 'Oles', 'Volusia', 'FL');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Alesia', 'Hixenbaugh', 'District of Columbia', 'DC');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Lai', 'Harabedian', 'Marin', 'CA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Brittni', 'Gillaspie', 'Ada', 'ID');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Raylene', 'Kampa', 'Elkhart', 'IN');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Flo', 'Bookamer', 'Box Butte', 'NE');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Jani', 'Biddy', 'King', 'WA');
INSERT INTO customer_location (first_name, last_name, county, state) VALUES ('Chauncey', 'Motley', 'Orange', 'FL');
